#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO
 
USER=root
HOME=/root
export USER HOME
case "$1" in
start)
echo "Starting xboxdrv"
#Insert your favoured settings for the xbox controller settings
su - $USER -c "xboxdrv --wid 0 --led 2 --silent --force-feedback --config /usr/share/xboxdrv/xpad-wireless.xboxdrv" &
sleep 1
su - $USER -c "xboxdrv --wid 1 --led 3 --silent --force-feedback --config /usr/share/xboxdrv/xpad-wireless.xboxdrv" &
sleep 1
su - $USER -c "xboxdrv --wid 2 --led 4 --silent --force-feedback --config /usr/share/xboxdrv/xpad-wireless.xboxdrv" &
sleep 1
su - $USER -c "xboxdrv --wid 3 --led 5 --silent --force-feedback --config /usr/share/xboxdrv/xpad-wireless.xboxdrv" &
sleep 1
;;

stop)
echo "Stopping xboxdrv"
killall /usr/bin/xboxdrv 
;;
esac
